import { NativeModules } from "react-native";

export function formatDate(timestamp) {
  const date = new Date(timestamp);

  return date.toLocaleTimeString("en-UK", {
    year: "2-digit",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

const deviceLanguage =
  Platform.OS === "ios"
    ? NativeModules.SettingsManager.settings.AppleLocale ||
      NativeModules.SettingsManager.settings.AppleLanguages[0] // iOS 13
    : NativeModules.I18nManager.localeIdentifier;

let lan;
let str = deviceLanguage;
let match = str.match(/^([a-z]{2})/i);
if (match) {
  lan = match[0];
} else {
  lan = "en";
}

export const lang = lan;

export const CURRENCY_INFO = [
  {
    code: "AED",
    name: "United Arab Emirates Dirham",
    arabic_name: "الدرهم الإماراتي",
    symbol: "د.إ",
    country: "United Arab Emirates",
  },
  {
    code: "AFN",
    name: "Afghan Afghani",
    arabic_name: "افغانى أفغانستان",
    symbol: "؋",
    country: "Afghanistan",
  },
  {
    code: "ALL",
    name: "Albanian Lek",
    arabic_name: "الليك الألباني",
    symbol: "L",
    country: "Albania",
  },
  {
    code: "ARS",
    name: "Argentine Peso",
    arabic_name: "البيزو الأرجنتيني",
    symbol: "$",
    country: "Argentina",
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    arabic_name: "الدولار الأسترالي",
    symbol: "$",
    country: "Australia",
  },
  {
    code: "BDT",
    name: "Bangladeshi Taka",
    arabic_name: "تاكا بنغلاديشي",
    symbol: "৳",
    country: "Bangladesh",
  },
  {
    code: "BGN",
    name: "Bulgarian Lev",
    arabic_name: "الليف البلغاري",
    symbol: "лв",
    country: "Bulgaria",
  },
  {
    code: "BHD",
    name: "Bahraini Dinar",
    arabic_name: "دينار بحريني",
    symbol: ".د.ب",
    country: "Bahrain",
  },
  {
    code: "BOB",
    name: "Bolivian Boliviano",
    arabic_name: "البوليفيانو البوليفي",
    symbol: "Bs.",
    country: "Bolivia",
  },
  {
    code: "BRL",
    name: "Brazilian Real",
    arabic_name: "الريال البرازيلي",
    symbol: "R$",
    country: "Brazil",
  },
  {
    code: "CAD",
    name: "Canadian Dollar",
    arabic_name: "الدولار الكندي",
    symbol: "$",
    country: "Canada",
  },
  {
    code: "CHF",
    name: "Swiss Franc",
    arabic_name: "الفرنك السويسري",
    symbol: "CHF",
    country: "Switzerland",
  },
  {
    code: "CLP",
    name: "Chilean Peso",
    arabic_name: "البيزو التشيلي",
    symbol: "$",
    country: "Chile",
  },
  {
    code: "CNY",
    name: "Chinese Yuan",
    arabic_name: "اليوان الصيني",
    symbol: "¥",
    country: "China",
  },
  {
    code: "COP",
    name: "Colombian Peso",
    arabic_name: "البيزو الكولومبي",
    symbol: "$",
    country: "Colombia",
  },
  {
    code: "CRC",
    name: "Costa Rican Colón",
    arabic_name: "الكولون الكوستاريكي",
    symbol: "₡",
    country: "Costa Rica",
  },
  {
    code: "CZK",
    name: "Czech Koruna",
    arabic_name: "الكورونا التشيكية",
    symbol: "Kč",
    country: "Czech Republic",
  },
  {
    code: "DKK",
    name: "Danish Krone",
    arabic_name: "الكرون الدنماركي",
    symbol: "kr",
    country: "Denmark",
  },
  {
    code: "DZD",
    name: "Algerian Dinar",
    arabic_name: "الدينار الجزائري",
    symbol: "د.ج",
    country: "Algeria",
  },
  {
    code: "EGP",
    name: "Egyptian Pound",
    arabic_name: "الجنيه المصري",
    symbol: "E£",
    country: "Egypt",
  },
  {
    code: "EUR",
    name: "Euro",
    arabic_name: "اليورو",
    symbol: "€",
    country: "Eurozone",
  },
  {
    code: "FJD",
    name: "Fijian Dollar",
    arabic_name: "الدولار الفيجي",
    symbol: "$",
    country: "Fiji",
  },
  {
    code: "GBP",
    name: "British Pound Sterling",
    arabic_name: "الجنيه الإسترليني",
    symbol: "£",
    country: "United Kingdom",
  },
  {
    code: "GEL",
    name: "Georgian Lari",
    arabic_name: "اللاري الجورجي",
    symbol: "₾",
    country: "Georgia",
  },
  {
    code: "GHS",
    name: "Ghanaian Cedi",
    arabic_name: "سيدي غانا",
    symbol: "GH₵",
    country: "Ghana",
  },
  {
    code: "HKD",
    name: "Hong Kong Dollar",
    arabic_name: "الدولار الهونغ كونغي",
    symbol: "$",
    country: "Hong Kong",
  },
  {
    code: "HRK",
    name: "Croatian Kuna",
    arabic_name: "الكونا الكرواتية",
    symbol: "kn",
    country: "Croatia",
  },
  {
    code: "HUF",
    name: "Hungarian Forint",
    arabic_name: "الفورينت المجري",
    symbol: "Ft",
    country: "Hungary",
  },
  {
    code: "IDR",
    name: "Indonesian Rupiah",
    arabic_name: "روبيه إندونيسية",
    symbol: "Rp",
    country: "Indonesia",
  },
  {
    code: "ILS",
    name: "Israeli New Shekel",
    arabic_name: "شيكل إسرائيلي جديد",
    symbol: "₪",
    country: "Israel",
  },
  {
    code: "INR",
    name: "Indian Rupee",
    arabic_name: "الروبية الهندية",
    symbol: "₹",
    country: "India",
  },
  {
    code: "IQD",
    name: "Iraqi Dinar",
    arabic_name: "الدينار العراقي",
    symbol: "ع.د",
    country: "Iraq",
  },
  {
    code: "ISK",
    name: "Icelandic Króna",
    arabic_name: "الكرونة الأيسلندية",
    symbol: "kr",
    country: "Iceland",
  },
  {
    code: "JOD",
    name: "Jordanian Dinar",
    arabic_name: "الدينار الأردني",
    symbol: "د.ا",
    country: "Jordan",
  },
  {
    code: "JPY",
    name: "Japanese Yen",
    arabic_name: "الين الياباني",
    symbol: "¥",
    country: "Japan",
  },
  {
    code: "KES",
    name: "Kenyan Shilling",
    arabic_name: "الشلن الكيني",
    symbol: "KSh",
    country: "Kenya",
  },
  {
    code: "KRW",
    name: "South Korean Won",
    arabic_name: "الون الكوري الجنوبي",
    symbol: "₩",
    country: "South Korea",
  },
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    arabic_name: "دينار كويتي",
    symbol: "د.ك",
    country: "Kuwait",
  },
  {
    code: "KZT",
    name: "Kazakhstani Tenge",
    arabic_name: "التينغ الكازاخستاني",
    symbol: "₸",
    country: "Kazakhstan",
  },
  {
    code: "LBP",
    name: "Lebanese Pound",
    arabic_name: "الليرة اللبنانية",
    symbol: "ل.ل",
    country: "Lebanon",
  },
  {
    code: "LKR",
    name: "Sri Lankan Rupee",
    arabic_name: "الروبية السريلانكية",
    symbol: "රු",
    country: "Sri Lanka",
  },
  {
    code: "MAD",
    name: "Moroccan Dirham",
    arabic_name: "الدرهم المغربي",
    symbol: "د.م.",
    country: "Morocco",
  },
  {
    code: "MDL",
    name: "Moldovan Leu",
    arabic_name: "الليو المولديفي",
    symbol: "L",
    country: "Moldova",
  },
  {
    code: "MMK",
    name: "Myanmar Kyat",
    arabic_name: "كيات ميانمار",
    symbol: "Ks",
    country: "Myanmar",
  },
  {
    code: "MNT",
    name: "Mongolian Tugrik",
    arabic_name: "التوغريك المنغولي",
    symbol: "₮",
    country: "Mongolia",
  },
  {
    code: "MOP",
    name: "Macanese Pataca",
    arabic_name: "الباتاكا الماكاوية",
    symbol: "MOP$",
    country: "Macau",
  },
  {
    code: "MXN",
    name: "Mexican Peso",
    arabic_name: "البيزو المكسيكي",
    symbol: "$",
    country: "Mexico",
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    arabic_name: "الرينغيت الماليزي",
    symbol: "RM",
    country: "Malaysia",
  },
  {
    code: "NGN",
    name: "Nigerian Naira",
    arabic_name: "النايرا النيجيرية",
    symbol: "₦",
    country: "Nigeria",
  },
  {
    code: "NOK",
    name: "Norwegian Krone",
    arabic_name: "الكرونة النرويجية",
    symbol: "kr",
    country: "Norway",
  },
  {
    code: "NZD",
    name: "New Zealand Dollar",
    arabic_name: "الدولار النيوزيلندي",
    symbol: "$",
    country: "New Zealand",
  },
  {
    code: "OMR",
    name: "Omani Rial",
    arabic_name: "الريال العماني",
    symbol: "ر.ع.",
    country: "Oman",
  },
  {
    code: "PEN",
    name: "Peruvian Nuevo Sol",
    arabic_name: "السول البيروفي الجديد",
    symbol: "S/.",
    country: "Peru",
  },
  {
    code: "PHP",
    name: "Philippine Peso",
    arabic_name: "البيزو الفلبيني",
    symbol: "₱",
    country: "Philippines",
  },
  {
    code: "PKR",
    name: "Pakistani Rupee",
    arabic_name: "الروبية الباكستانية",
    symbol: "₨",
    country: "Pakistan",
  },
  {
    code: "PLN",
    name: "Polish Zloty",
    arabic_name: "الزلوتي البولندي",
    symbol: "zł",
    country: "Poland",
  },
  {
    code: "PYG",
    name: "Paraguayan Guarani",
    arabic_name: "الغواراني الباراغوي",
    symbol: "₲",
    country: "Paraguay",
  },
  {
    code: "QAR",
    name: "Qatari Rial",
    arabic_name: "الريال القطري",
    symbol: "ر.ق",
    country: "Qatar",
  },
  {
    code: "RON",
    name: "Romanian Leu",
    arabic_name: "الليو الروماني",
    symbol: "lei",
    country: "Romania",
  },
  {
    code: "RSD",
    name: "Serbian Dinar",
    arabic_name: "الدينار الصربي",
    symbol: "дин.",
    country: "Serbia",
  },
  {
    code: "RUB",
    name: "Russian Ruble",
    arabic_name: "الروبل الروسي",
    symbol: "₽",
    country: "Russia",
  },
  {
    code: "SAR",
    name: "Saudi Riyal",
    arabic_name: "الريال السعودي",
    symbol: "ر.س",
    country: "Saudi Arabia",
  },
  {
    code: "SEK",
    name: "Swedish Krona",
    arabic_name: "الكرونا السويدية",
    symbol: "kr",
    country: "Sweden",
  },
  {
    code: "SGD",
    name: "Singapore Dollar",
    arabic_name: "الدولار السنغافوري",
    symbol: "$",
    country: "Singapore",
  },
  {
    code: "THB",
    name: "Thai Baht",
    arabic_name: "البات التايلاندي",
    symbol: "฿",
    country: "Thailand",
  },
  {
    code: "TRY",
    name: "Turkish Lira",
    arabic_name: "الليرة التركية",
    symbol: "₺",
    country: "Turkey",
  },
  {
    code: "TWD",
    name: "New Taiwan Dollar",
    arabic_name: "الدولار التايواني الجديد",
    symbol: "NT$",
    country: "Taiwan",
  },
  {
    code: "TZS",
    name: "Tanzanian Shilling",
    arabic_name: "الشلن التنزاني",
    symbol: "TSh",
    country: "Tanzania",
  },
  {
    code: "UAH",
    name: "Ukrainian Hryvnia",
    arabic_name: "الهريفنيا الأوكرانية",
    symbol: "₴",
    country: "Ukraine",
  },
  {
    code: "USD",
    name: "United States Dollar",
    arabic_name: "الدولار الأمريكي",
    symbol: "$",
    country: "United States",
  },
  {
    code: "VEF",
    name: "Venezuelan Bolívar",
    arabic_name: "البوليفار الفنزويلي",
    symbol: "Bs.",
    country: "Venezuela",
  },
  {
    code: "VND",
    name: "Vietnamese Dong",
    arabic_name: "الدونغ الفيتنامي",
    symbol: "₫",
    country: "Vietnam",
  },
  {
    code: "ZAR",
    name: "South African Rand",
    arabic_name: "الراند الجنوب أفريقي",
    symbol: "R",
    country: "South Africa",
  },
];
